name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Debug info
        run: |
          echo "Running on $(uname -a)"
          python --version
          pip --version
          echo "Repository files:" 
          ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m pip show pytest || true
      - name: Run tests (target folder)
        run: |
          echo "Listing test folder contents:"
          ls -la qabunker/qa/automation || true
          python -m pytest qabunker/qa/automation -v
